// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LayoutTry.Models;

public partial class TProduct
{
    public int FId { get; set; }

    public string FName { get; set; }

    public int? FQty { get; set; }

    public decimal? FCost { get; set; }

    public decimal? FPrice { get; set; }

    public string FImagePath { get; set; }
}